### ISSUE TITLE
Timeline for releasing YFCC15M long captions?

### ISSUE THREAD

**Issue by kim-sanghwan** [zyf0619sjtu/DreamLIP#11]
Great and awesome works done by you. 
I would like to cite and use your datasets. 
Could you tell me when you will be able to release the YFCC15M dataset approximately?
Thank you in advance.

**Comment by zkcys001** [comment]
hello, we release long captions of yfcc15m in google drive: https://drive.google.com/file/d/1lCgsIZSupqhO-vFnoi_ORur0xn7xfSp6/view?usp=drive_link
