### ISSUE TITLE
Releasing the DreamLIP model

### ISSUE THREAD

**Issue by vishaal27** [zyf0619sjtu/DreamLIP#2]
Hi,

Great work! Are you planning to release the final trained model and would it be compatible with huggingface transformers / open_clip?

Thanks!

**Comment by zkcys001** [comment]
Hello, we plan to upload the pretrained weight of VIT-B/16 and VIT-B/32 pretrained in CC3M, CC12M, YFCC15M, and merged-30M. These pretrained models are compatible with open_clip.

Best
Kecheng

**Comment by Maitreyapatel** [comment]
Great work @zkcys001! 
Do you have expected timeline on when the models will be released?

Thanks!

**Comment by zkcys001** [comment]
We will release the code, pre-trained model and CC12M dataset in this week (before 7.15)
