### ISSUE TITLE
Questions about the released dataset

### ISSUE THREAD

**Issue by Espere-1119-Song** [zyf0619sjtu/DreamLIP#3]
Hi, thanks for your great contribution of the dataset. When I download  cc3m, the index of my images seems different from yours.

![image](https://github.com/zyf0619sjtu/DreamLIP/assets/77435739/f487fc60-c791-4b03-9aa9-51a8ec4db729)

for example, when point to '0000000/0000008.jpg', the caption of mine is "# of the sports team skates against sports team during their game .", while the 'raw_caption' of yours is ''modern luxe has a very simple look , and offers a bold monogram of the couple 's initials .".  I download CC3M via img2dataset.

I think providing another file with 'image_path' and its respective 'url' is a potential solution. Can you provide it? Thanks!!

**Comment by zkcys001** [comment]
It is a good question. 

I have provided a json file in google drive, and the example of this file is: 
![image](https://github.com/zyf0619sjtu/DreamLIP/assets/20808715/105f3a2f-3b5a-4c62-8af6-bedcd99531e0)

https://drive.google.com/file/d/1iRaYLxrW_pHODzMpvIvjSNfpsM_9OGiL/view?usp=sharing

Moreover, we will release CC12M in this week~

Best
Kecheng

**Comment by kim-sanghwan** [comment]
Thank you for your great work. I tried to used your google drive link but it shows me below.
Can you share the valid link for "cc3m_path2url.json" again?
![image](https://github.com/user-attachments/assets/a076cfb8-adf3-45d5-9ca2-c6663be7a6fa)

**Comment by zkcys001** [comment]
We have updated the CC3M&12M files as follows: 3 types of short captions have been added, and we replace 'path' to image ‘url’ in these csv files.

CC3M:
https://drive.google.com/file/d/1RPcFS8jrVolA9RzHXD581E8BxR7jYDap/view?usp=sharing
CC12M:
https://drive.google.com/file/d/12iUhceznPNWd-l_bGSF5rSnzdruP4Jtr/view?usp=sharing
