### ISSUE TITLE
code and dataset

### ISSUE THREAD

**Issue by buchannn** [zyf0619sjtu/DreamLIP#5]
Thank you for your work. 

When will the code and dataset be released?

**Comment by buchannn** [comment]
And when will the pre-trained model be released?

**Comment by zkcys001** [comment]
We will release the code, pre-trained model and CC12M dataset in this week (before 7.15)

**Comment by lezhang7** [comment]
Thanks for the great work, could you also release code on how to process cc3m images?

**Comment by ivonajdenkoska** [comment]
Hi. Thanks for your great work! I have the same question as @lezhang7 , are you planning to release the code for downloading/processing the CC3M/CC12M/YFCC15M?

**Comment by zkcys001** [comment]
Hello, you can download the images of CC3M/CC12M from huggingface:

https://huggingface.co/datasets/dalle-mini/YFCC100M_OpenAI_subset
https://huggingface.co/datasets/pixparse/cc3m-wds
https://huggingface.co/datasets/pixparse/cc12m-wds

I'm sorry that we hava no plan to release the code of image captioning.
