### ISSUE TITLE
Questions about Subcaption-specific Grouping Loss

### ISSUE THREAD

**Issue by lezhang7** [zyf0619sjtu/DreamLIP#6]
Hi,

Thanks for your wonderful work, it's so inspiring and encouraging. I have some questions regarding Subcaption-specific Grouping Loss, is it inspired from [SPARC](https://arxiv.org/pdf/2401.09865)? And since this operation would creat a larger matrix with shape of B,n,n where n is number of text tokens, to what extent would it demand GPU memory for training? 

Best

**Comment by zkcys001** [comment]
Subcaption-specific Grouping Loss is it inspired from FILIP and SPARC. n is number of sub-captions, n<=20.

[1] Filip: fine-grained interactive language-image pre-training
[2] Improving fine-grained understanding in image-text pre-training
