### ISSUE TITLE
Which dataset class are you using for training

### ISSUE THREAD

**Issue by sean-xr** [zyf0619sjtu/DreamLIP#7]
Dear Authors,

Thx for sharing this great work! In your data.py, you implemented dataset class for all types of data, csv, txt etc. May I ask which dataset class you are using for your training settings in difference datasets?

Best regards

**Comment by zkcys001** [comment]
Hello, we have used the csv class in all datasets. We will release the training code once the internal review is completed.

**Comment by sean-xr** [comment]
Thx for the answer!
